### ISSUE TITLE
Flick not working in IphoneX with iOS 11.4.1

### ISSUE THREAD

**Issue by aryalakshmi** [isonic1/flick#41]
Hi All,

I am facing issue with Flick on IphoneX. All generated videos are of 0bytes.

It was working fine on iphone 6.

Command used:
flick video -a start -p ios -u $udid -n test1 -o /Users/digitalhome/Documents/
flick video -a stop -p ios -u $udid -n test1 -o /Users/digitalhome/Documents/

Digitals-MacBook-Pro-2:digitalhome$ ls -lrt /Users/digitalhome/Documents/test1.mp4 
-rw-r--r--  1 digitalhome  staff  0 Aug 21 16:41 /Users/digitalhome/Documents/test1.mp4

Can someone help me with this issue?

**Comment by aryalakshmi** [comment]
hi,
can someone please help with this issue?

thanks,
Arya

**Comment by aryalakshmi** [comment]
Hi,

Is there any fix.for this issue :(

**Comment by isonic1** [comment]
I just released a new version flick 0.4.5. Thank you @gdimitris for submitting this PR! @aryalakshmi please let me know if this works for you now.

**Comment by aryalakshmi** [comment]
hi,

I have updated flick but still it doesnt work

Digitals-MBP-2:videos_whw root# flick --version
eflick 0.4.5

Digitals-MBP-2:videos_whw root# flick video -a start -p ios 

Starting Recoder!!!
error: undefined method `include?' for nil:NilClass. Use --trace to view backtrace
Digitals-MBP-2:videos_whw root# flick video -a stop -p ios 

Stopping Recorder!!!
error: undefined method `include?' for nil:NilClass. Use --trace to view backtrace


#############################
Digitals-MBP-2:videos_whw root# flick video -a start -p ios -u XXXXXXXXX --trace

Starting Recoder!!!
/Library/Ruby/Gems/2.3.0/gems/commander-4.4.6/lib/commander/user_interaction.rb:359:in `method_missing': undefined method `include?' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.3.0/gems/flick-0.4.5/lib/flick/system.rb:17:in `block in find_pid'
	from /Library/Ruby/Gems/2.3.0/gems/flick-0.4.5/lib/flick/system.rb:17:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/flick-0.4.5/lib/flick/system.rb:17:in `find_all'
	from /Library/Ruby/Gems/2.3.0/gems/flick-0.4.5/lib/flick/system.rb:17:in `find_pid'
	from /Library/Ruby/Gems/2.3.0/gems/flick-0.4.5/lib/flick/system.rb:37:in `kill_process'
	from /Library/Ruby/Gems/2.3.0/gems/flick-0.4.5/lib/flick/video.rb:109:in `start_screenshot_record'
	from /Library/Ruby/Gems/2.3.0/gems/flick-0.4.5/lib/flick/video.rb:50:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/flick-0.4.5/lib/flick/video.rb:34:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/flick-0.4.5/bin/flick:34:in `block (2 levels) in <top (required)>'
	from /Library/Ruby/Gems/2.3.0/gems/commander-4.4.6/lib/commander/command.rb:182:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-4.4.6/lib/commander/runner.rb:446:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/commander-4.4.6/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-4.4.6/lib/commander/import.rb:5:in `block in <top (required)>'
Digitals-MBP-2:videos_whw root#

**Comment by aryalakshmi** [comment]
Hi, Thanks a lot for your solution. Its working now after uninstall and reinstall of gem and flick.

**Comment by isonic1** [comment]
@aryalakshmi please thank @gdimitris. :)
